import { storageOwner } from "./storageOwner.js";
import type { StorageTasks } from "./storageTasks.js";

function command<K extends keyof StorageTasks>(name: K) {
  return (...args: Parameters<StorageTasks[K]>): Promise<ReturnType<StorageTasks[K]>> => storageOwner.run(name, args);
}
export const initialize = command("initialize");
export const flush = command("flush");
export const finish = command("finish");
export const log = command("log");
export const readAssetFile = command("readAssetFile");
export const fileExists = command("fileExists");
export const readSourceMetadata = command("readSourceMetadata");
export const listWorkspaces = command("listWorkspaces");
export const getWorkspace = command("getWorkspace");
export const openOrCreateWorkspace = command("openOrCreateWorkspace");
export const updateWorkspace = command("updateWorkspace");
export const deleteWorkspace = command("deleteWorkspace");
export const getSettings = command("getSettings");
export const saveSettings = command("saveSettings");
export const getRoleCall = command("getRoleCall");
export const getAnthropicSettingsForClient = command("getAnthropicSettingsForClient");
export const saveAnthropicSettings = command("saveAnthropicSettings");
export const getTargets = command("getTargets");
export const saveTargets = command("saveTargets");
export const getAnalysisPrompts = command("getAnalysisPrompts");
export const saveAnalysisPrompts = command("saveAnalysisPrompts");
export const getGenerationPrompts = command("getGenerationPrompts");
export const saveGenerationPrompts = command("saveGenerationPrompts");
export const clearCache = command("clearCache");
export const rebuildIndex = command("rebuildIndex");
export const queueWorkspaceContent = (wsId: string, id: string, content: string) => storageOwner.run("queueWorkspaceContent", [wsId, id, content, new Date()]);
export const queueWorkspaceMetadata = (wsId: string, id: string, edits: unknown) => storageOwner.run("queueWorkspaceMetadata", [wsId, id, edits, new Date()]);
export const queueContent = (...args: Parameters<StorageTasks["queueContent"]>) => storageOwner.run("queueContent", [args[0], args[1], args[2], args[3] ?? new Date()]);
export const queueMetadata = (...args: Parameters<StorageTasks["queueMetadata"]>) => storageOwner.run("queueMetadata", [args[0], args[1], args[2], args[3] ?? new Date()]);
export const flushPostEdits = command("flushPostEdits");
export const getPost = command("getPost");
export const createPost = command("createPost");
export const updatePost = command("updatePost");
export const recordAssetChange = command("recordAssetChange");
export const changeStatus = command("changeStatus");
export const setLocked = command("setLocked");
export const getPostSummary = command("getPostSummary");
export const listReferrers = command("listReferrers");
export const postExists = command("postExists");
export const renameTarget = command("renameTarget");
export const refreshIndex = command("refreshIndex");
export const listByStatus = command("listByStatus");
export const countByStatus = command("countByStatus");
export const holdPendingFlushes = command("holdPendingFlushes");
export const resumePendingFlushes = command("resumePendingFlushes");
export const listAssets = command("listAssets");
export const saveAssetFile = command("saveAssetFile");
export const deleteAsset = command("deleteAsset");
export const getUiState = command("getUiState");
export const updateUiState = command("updateUiState");
export const getAppSettingsLoad = command("getAppSettingsLoad");
export const saveAppSettings = command("saveAppSettings");
export const currentRecordsSession = command("currentRecordsSession");
export const writeProviderCall = command("writeProviderCall");

export const setContentSaveListener = storageOwner.onContentSave.bind(storageOwner);
export const deletePost = command("deletePost");
